# Generated by Django 3.1.5 on 2021-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quiz_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
