# Generated by Django 3.1.6 on 2021-03-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdb', '0004_auto_20210302_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
