# Generated by Django 3.1.6 on 2021-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdb', '0005_auto_20210308_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
