# Generated by Django 3.1.6 on 2021-03-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdb', '0006_auto_20210308_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
