# Generated by Django 3.1.6 on 2021-03-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdb', '0007_auto_20210309_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=140)),
                ('option1', models.CharField(default='SOME STRING', max_length=100)),
                ('option2', models.CharField(default='SOME STRING', max_length=100)),
                ('option3', models.CharField(default='SOME STRING', max_length=100)),
                ('option4', models.CharField(default='SOME STRING', max_length=100)),
                ('correct_answer', models.CharField(max_length=1)),
                ('solution', models.CharField(max_length=210)),
                ('quiz_id', models.IntegerField()),
            ],
        ),
    ]
