# Generated by Django 3.1.6 on 2021-03-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdb', '0008_teacher_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
